version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    # depends_on:
    #   - db

#   db:
#     image: postgres:15
#     restart: always
#     environment:
#       POSTGRES_DB: mydb
#       POSTGRES_USER: devuser
#       POSTGRES_PASSWORD: devpass
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
