version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: team8       # replace with your username
      POSTGRES_PASSWORD: team8   # replace with your password
      POSTGRES_DB: team8_db    # replace with your database name
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"

volumes:
  postgres: