version: '3.8'
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  db: # Ready for recommender, conatins example data, need to update for server
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ac
      POSTGRES_USER: ac
      POSTGRES_PASSWORD: ac
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  recommender: # Updated for production but need to test
    build:
      context: ./recommender
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_NAME= ac
      - DB_USER= ac
      - DB_PASSWORD= ac
      - MAX_FRIENDS_RECOMMENDATIONS=5
      - MAX_GROUPS_RECOMMENDATIONS=1
      - MAX_CLUSTERS=100
    depends_on:
      db:
        condition: service_healthy
    
  server: # Developing
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_PORT}:5000"
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy
      recommender:
        condition: service_healthy

volumes:
  postgres: