version: '3.8'
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "${FRONTEND_PORT}:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      # - postgres:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  recommender:
    build:
      context: ./recommender
      dockerfile: Dockerfile.dev
    ports:
      - "${RS_PORT}:5000"
    volumes:
      - ./recommender:/app
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - MAX_FRIENDS_RECOMMENDATIONS=${MAX_FRIENDS_RECOMMENDATIONS}
      - MAX_GROUPS_RECOMMENDATIONS=${MAX_GROUPS_RECOMMENDATIONS}
      - DB_MIN_CONN=${DB_MIN_CONN}
      - DB_MAX_CONN=${DB_MAX_CONN}
    depends_on:
      db:
        condition: service_healthy

# volumes:
#   postgres: